// <auto-generated />
using System;
using IdentityService.Infrastructure.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityServiceDbContext))]
    [Migration("20251015212454_createdDate")]
    partial class createdDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.AccountContext.AccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", "identity");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("departments", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("groups", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PostEntity", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("posts", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("PublisherId");

                    b.HasIndex("PostId");

                    b.ToTable("publishers", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("SpecialtyTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecialtyId");

                    b.ToTable("specialties", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("students", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("users", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PostEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", "Department")
                        .WithMany("Posts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.PostEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.UserEntity", "User")
                        .WithOne("PublisherProfile")
                        .HasForeignKey("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", "PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.UserEntity", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.UserEntity", b =>
                {
                    b.Navigation("PublisherProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
