// <auto-generated />
using System;
using IdentityService.Infrastructure.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityServiceDbContext))]
    partial class IdentityServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.AccountContext.AccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", "identity");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("DepartmentId");

                    b.ToTable("departments", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("integer")
                        .HasColumnName("course");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("integer")
                        .HasColumnName("number_group");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id");

                    b.HasKey("GroupId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("groups", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PostEntity", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("PostId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("posts", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("PublisherId");

                    b.HasIndex("PostId");

                    b.ToTable("publishers", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("SpecialtyTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialty_title");

                    b.HasKey("SpecialtyId");

                    b.ToTable("specialties", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("students", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("UserId");

                    b.ToTable("users", "profile");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PostEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", "Department")
                        .WithMany("Posts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.PostEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.UserEntity", "User")
                        .WithOne("PublisherProfile")
                        .HasForeignKey("IdentityService.Infrastructure.Entites.UserContext.PublisherEntity", "PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", b =>
                {
                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Infrastructure.Entites.UserContext.UserEntity", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("IdentityService.Infrastructure.Entites.UserContext.StudentEntity", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.DepartmentEntity", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.SpecialtyEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Entites.UserContext.UserEntity", b =>
                {
                    b.Navigation("PublisherProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
